// logs.html 안에 비가시(<script type="text/markdown">)로 박히는 AI 소비 매뉴얼.
// 정적 평문 — 데이터 위치·디코드 레시피·각 필드 소비법을 설명한다. 데이터는 복제하지 않는다.
// 주의: 본문에 리터럴 `</scr`+`ipt`를 넣지 말 것(script 조기 종료). 백틱·${ }도 피해 일반 문자열로 작성.
// 레시피는 base64 문자셋 앵커로 매치한다 — 매뉴얼은 데이터(<body>)보다 앞(<head>)에 있어
// 첫-매치 정규식이면 매뉴얼 내 레시피 텍스트 자신을 잡아 실패하기 때문.
export const AI_LOGS_MANUAL = [
  "You are reading a BugShot debug capture (logs.html), a self-contained bug report",
  "exported from the BugShot Chrome extension. The visible page is a human viewer;",
  "the real data is embedded as described here. Read this first, then consume the data.",
  "",
  "## How to read the data",
  "All captured data is in the script element with id __BUGSHOT_DATA__",
  "(type application/gzip-base64). Its text is base64-encoded gzip of a JSON object.",
  "To read it: base64-decode the text, gunzip it, then JSON.parse the UTF-8 result.",
  "NOTE: this manual appears BEFORE the data in the file, so match the base64 by its",
  "character set (not the first occurrence of the id) to avoid matching this recipe text.",
  "",
  "Python:",
  "    import re, base64, gzip, json",
  '    html = open(PATH_TO_THE_UPLOADED_FILE, encoding="utf-8").read()',
  "    b64 = re.search(r'id=\"__BUGSHOT_DATA__\"[^>]*>([A-Za-z0-9+/=\\s]+)', html).group(1)",
  '    data = json.loads(gzip.decompress(base64.b64decode("".join(b64.split()))))',
  "",
  "Node.js:",
  '    const html = require("fs").readFileSync(PATH_TO_THE_UPLOADED_FILE, "utf8");',
  '    const b64 = html.match(/id="__BUGSHOT_DATA__"[^>]*>([A-Za-z0-9+\\/=\\s]+)/)[1];',
  '    const zlib = require("zlib");',
  '    const data = JSON.parse(zlib.gunzipSync(Buffer.from(b64, "base64")).toString("utf8"));',
  "",
  "If you have no code-execution environment, ask the user to run the snippet above on",
  "the file and paste back the decoded JSON.",
  "",
  "A second script element with id __BUGSHOT_META__ (type application/json) is plain",
  "JSON, no decoding: { version, createdAt, pageUrl, issueTitle?, issueKey?, issueUrl? }.",
  "createdAt is an ISO 8601 string (NOT epoch ms). issueKey/issueUrl are present and",
  "non-empty only if the bug was filed to a tracker (Jira/GitHub/etc.); empty string otherwise.",
  "",
  "## What's inside (decoded JSON top-level keys; any may be null)",
  "- report  — READ THIS FIRST for bug context. The human/AI-drafted issue: title,",
  "  env (array of { label, value }), and sections (array of { id, label, renderAs, value };",
  "  enabled sections only, so they vary — e.g. description / steps to reproduce / expected",
  "  result / notes). report.copy.markdown is the whole thing as one markdown string — if",
  "  parsing the structure is awkward, just read report.copy.markdown. Tells you WHAT the bug is.",
  "- consoleLog.entries[] — console messages: level (log/info/warn/error/debug),",
  "  timestamp (epoch ms), args (text, may include a stack), stack?, pageUrl.",
  "- networkLog.requests[] — requests: method, url, status, statusText, durationMs,",
  "  startTime (epoch ms), requestHeaders, responseHeaders, requestBody?, responseBody?,",
  "  contentType, phase (pending/complete/error). Sensitive header values are masked as",
  "  ***[len:N]. Bodies may be objects like { kind: \"truncated\"|\"binary\"|... } when not",
  '  inlined. WebSocket connections appear as method "WS", status 101, with a',
  "  webSocket.frames[] array.",
  "- actionLog.entries[] — user action timeline: kind (click/navigation/input/keypress/",
  "  toggle/select/drag), timestamp (epoch ms), pageUrl, plus kind-specific fields",
  "  (target/selector, fromUrl/toUrl, fieldLabel/value, ...). Reconstruct what the user did.",
  "- video — 30s screen replay { dataUrl, startedAt, thumbnail? }. dataUrl is an MP4",
  "  (H.264) data URL; startedAt (epoch ms) is the shared anchor to align video time with",
  "  log timestamps. If you can process MP4, decode dataUrl; otherwise use the timeline + report.",
  "- screenshot — static image { dataUrl } (image data URL). Decode if you support images.",
  "",
  "consoleLog/networkLog/actionLog are null ONLY when this capture mode does not collect",
  "that log — null means NOT COLLECTED, never zero events. When the key is an object its",
  "totalSeen/captured are authoritative: empty entries/requests with totalSeen 0 means the",
  "log was watched and genuinely nothing happened (e.g. no console errors), which is a real",
  "signal — do not read it as missing data.",
  "Each log also has totalSeen vs captured and",
  "networkLog.warnings (e.g. MEMORY_CAPPED, BODY_TRUNCATED, ENTRY_CAPPED, WS_FRAMES_CAPPED).",
  "If captured < totalSeen or warnings are present, the log is partial/truncated — say so",
  "and avoid concluding from absence of an entry.",
  "",
  "All log timestamps are epoch milliseconds — correlate console/network/action/video by time.",
  "preArm: true on an entry means it was captured very early in page load.",
  "Respond in the user's language.",
].join("\n");
