import type { BgRequest } from "@/types/messages";

// handleMessage 디스패치 게이트(index.ts onMessage)가 화이트리스트로 쓰는 메시지 타입 집합.
// Record<BgRequest["type"], true>로 정의해 union의 모든 메시지 타입이 빠짐없이 등록되도록
// 컴파일 타임에 강제한다 — 신규 플랫폼 메시지를 여기에 빠뜨리면 typecheck가 실패한다.
// (과거 asana 연동이 이 등록 누락으로 런타임에서 전량 차단된 회귀를 영구 방지.)
const BG_REQUEST_TYPE_MAP: Record<BgRequest["type"], true> = {
  ping: true,
  captureVisibleTab: true,
  "oauth.start": true,
  "oauth.available": true,
  "jira.myself": true,
  "jira.listProjects": true,
  "jira.listIssueTypes": true,
  "jira.listPriorities": true,
  "jira.searchUsers": true,
  "jira.getIssueStatus": true,
  "jira.getTransitions": true,
  "jira.transitionIssue": true,
  "jira.searchEpics": true,
  "jira.submitIssue": true,
  "github.oauth.available": true,
  "github.startOAuth": true,
  "github.testPat": true,
  "github.disconnect": true,
  "github.getMyself": true,
  "github.searchRepos": true,
  "github.getLabels": true,
  "github.searchAssignees": true,
  "github.uploadFiles": true,
  "github.submitIssue": true,
  "github.getIssueStatus": true,
  "github.updateIssueState": true,
  "linear.oauth.available": true,
  "linear.startOAuth": true,
  "linear.testApiKey": true,
  "linear.disconnect": true,
  "linear.getMyself": true,
  "linear.getTeams": true,
  "linear.getProjects": true,
  "linear.getLabels": true,
  "linear.getMembers": true,
  "linear.submitIssue": true,
  "linear.uploadFile": true,
  "linear.createAttachment": true,
  "linear.getIssueStatus": true,
  "linear.getWorkflowStates": true,
  "linear.updateIssueState": true,
  "notion.oauth.available": true,
  "notion.startOAuth": true,
  "notion.testToken": true,
  "notion.disconnect": true,
  "notion.getMyself": true,
  "notion.listUsers": true,
  "notion.searchDatabases": true,
  "notion.getDatabaseSchema": true,
  "notion.uploadFile": true,
  "notion.submitPage": true,
  "notion.getPageStatus": true,
  "notion.updatePageStatus": true,
  "gitlab.oauth.available": true,
  "gitlab.startOAuth": true,
  "gitlab.testPat": true,
  "gitlab.disconnect": true,
  "gitlab.getMyself": true,
  "gitlab.searchProjects": true,
  "gitlab.getLabels": true,
  "gitlab.searchAssignees": true,
  "gitlab.uploadFiles": true,
  "gitlab.submitIssue": true,
  "gitlab.getIssueStatus": true,
  "gitlab.updateIssueState": true,
  "gitlab.updateIssueDescription": true,
  "asana.oauth.available": true,
  "asana.startOAuth": true,
  "asana.testPat": true,
  "asana.disconnect": true,
  "asana.getMyself": true,
  "asana.getWorkspaces": true,
  "asana.searchProjects": true,
  "asana.searchAssignees": true,
  "asana.uploadFiles": true,
  "asana.submitIssue": true,
  "asana.updateTaskNotes": true,
  "asana.getTaskStatus": true,
  "asana.setCompleted": true,
  "analytics.capture": true,
};

export const BG_REQUEST_TYPES: ReadonlySet<string> = new Set(
  Object.keys(BG_REQUEST_TYPE_MAP),
);
