import { IDBFactory, IDBKeyRange } from "fake-indexeddb";
import { beforeEach, afterEach, expect, it, vi } from "vitest";
import type { CreatedDestination, SubmissionRecoveryMeta } from "@/types/attachment";
import type { IssueRecord } from "@/store/issues-store";

let recovery: typeof import("../submissionRecovery");
let db: typeof import("@/store/blob-db");
let store: typeof import("@/store/issues-store");
const issue = (): IssueRecord => ({ id: "i", title: "Report", platform: "github", status: "draft", createdAt: 1, updatedAt: 1, pageUrl: "", draft: { title: "Report", sections: {} }, snapshot: { before: false, after: false }, captureMode: "freeform" });
const destination: CreatedDestination = { platform: "github", key: "#1", url: "https://github.com/o/r/issues/1", locator: { owner: "o", repo: "r", number: "1" } };
const meta = (): SubmissionRecoveryMeta => ({ attemptId: "a", issueId: "i", title: "Report", platform: "github", createdAt: 1, expiresAt: Date.now() + 2592000000, updatedAt: 1, phase: "prepared", files: [], results: [] });
beforeEach(async () => {
  vi.resetModules();
  vi.stubGlobal("indexedDB", new IDBFactory());
  vi.stubGlobal("IDBKeyRange", IDBKeyRange);
  vi.stubGlobal("chrome", { storage: { local: { get: vi.fn(async () => ({})), set: vi.fn(async () => {}) }, session: { get: vi.fn(async () => ({})), set: vi.fn(async () => {}) } }, runtime: { sendMessage: vi.fn() } });
  db = await import("@/store/blob-db");
  store = await import("@/store/issues-store");
  recovery = await import("../submissionRecovery");
  store.useIssuesStore.setState({ issues: [issue()] });
});
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); });

it.each(["inline", "video", "capture", "user"] as const)("missing %s source prevents any external call", async (kind) => {
  const remote = vi.fn();
  await expect(recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [{ id: kind, kind, filename: "file", contentType: "image/png", source: { kind: "original", store: "images", key: "absent" } }] }).then(remote)).rejects.toThrow();
  expect(remote).not.toHaveBeenCalled();
  expect(await db.listSubmissionRecoveries()).toEqual([]);
});
it("freezes generated bytes and stores originals only by their original keys", async () => {
  await db.saveAttachmentBlob("i", "pdf", new Blob(["original"], { type: "application/pdf" }));
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [
    { id: "user:pdf", kind: "user", filename: "logs.html", contentType: "application/pdf", source: { kind: "original", store: "attachments", key: "i:pdf" } },
    { id: "logs", kind: "logs", filename: "logs.html", contentType: "text/html", blob: new Blob(["first"], { type: "text/html" }) },
  ] });
  expect(prepared.meta.files[0].source).toEqual({ kind: "original", store: "attachments", key: "i:pdf" });
  expect(await (await db.readRecoveryFile(prepared.meta, "logs"))!.text()).toBe("first");
  expect(prepared.files.map((f) => f.id)).toEqual(["user:pdf", "logs"]);
});
it("waits for creating and created checkpoints before subsequent adapter work", async () => {
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [] });
  const result = await recovery.runSubmissionRecovery(prepared, async (progress) => {
    await progress.beforeCreate();
    expect((await db.readSubmissionRecovery("i"))?.phase).toBe("creating");
    await progress.created(destination);
    expect((await db.readSubmissionRecovery("i"))?.destination).toEqual(destination);
    return { key: "#1", url: destination.url!, attachments: [] };
  });
  expect(result.key).toBe("#1");
  expect(store.useIssuesStore.getState().issues[0].status).toBe("submitted");
  expect(await db.readSubmissionRecovery("i")).toBeNull();
});
it("preserves created identity when the upload RPC throws", async () => {
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [{ id: "logs", kind: "logs", filename: "logs.html", contentType: "text/html", blob: new Blob(["logs"]) }] });
  const create = vi.fn(async () => destination);
  const result = await recovery.runSubmissionRecovery(prepared, async (progress) => {
    await progress.beforeCreate();
    await progress.created(await create());
    throw new Error("upload disconnected");
  });
  expect(create).toHaveBeenCalledTimes(1);
  expect(result).toMatchObject({ key: "#1", recovery: { state: "partial" } });
  expect((await db.readSubmissionRecovery("i"))?.files).toHaveLength(1);
  expect(store.useIssuesStore.getState().issues[0]).toMatchObject({ status: "submitted", submissionRecoveryId: prepared.meta.attemptId });
});
it("a failed submitted write retains a complete journal and bytes for reconciliation", async () => {
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [] });
  vi.mocked(chrome.storage.local.set).mockRejectedValueOnce(new Error("quota"));
  await expect(recovery.runSubmissionRecovery(prepared, async (p) => { await p.beforeCreate(); await p.created(destination); return { key: "#1", url: destination.url!, attachments: [] }; })).rejects.toThrow("quota");
  expect((await db.readSubmissionRecovery("i"))?.phase).toBe("complete");
  await recovery.reconcileSubmissionRecovery();
  expect(store.useIssuesStore.getState().issues[0].status).toBe("submitted");
  expect(await db.readSubmissionRecovery("i")).toBeNull();
});
it("reconciles interrupted creation as unknown and blocks stale drafts", async () => {
  await db.beginSubmissionRecovery(meta(), new Map());
  await db.checkpointSubmission("i", "a", { phase: "creating", results: [] });
  await recovery.reconcileSubmissionRecovery();
  expect((await db.readSubmissionRecovery("i"))?.phase).toBe("unknown");
  expect(store.canSubmitIssue(store.useIssuesStore.getState().issues[0])).toBe(false);
  const remote = vi.fn();
  await expect(store.withIssueSubmitGuard("i", remote)).rejects.toThrow();
  expect(remote).not.toHaveBeenCalled();
});
it("unknown confirmation re-reads and refuses a created destination", async () => {
  await db.beginSubmissionRecovery(meta(), new Map());
  await db.checkpointSubmission("i", "a", { phase: "creating", results: [] });
  await db.checkpointSubmission("i", "a", { phase: "unknown", results: [] });
  await db.checkpointSubmission("i", "a", { phase: "created", results: [], destination });
  await expect(recovery.confirmSubmissionNotRegistered("i", "a")).rejects.toThrow();
  expect((await db.readSubmissionRecovery("i"))?.destination).toEqual(destination);
});
it("expiry drops bytes but retains file names and remote state", async () => {
  const m = meta();
  m.expiresAt = 2;
  m.files = [{ id: "logs", kind: "logs", filename: "logs.html", contentType: "text/html", source: { kind: "generated", key: "file:a:logs" } }];
  await db.beginSubmissionRecovery(m, new Map([["file:a:logs", new Blob(["private"])]]));
  await db.checkpointSubmission("i", "a", { phase: "creating", results: [] });
  await db.checkpointSubmission("i", "a", { phase: "created", destination, results: [] });
  await recovery.reconcileSubmissionRecovery();
  const current = (await db.readSubmissionRecovery("i"))!;
  expect(current.files[0].filename).toBe("logs.html");
  expect(current.destination).toEqual(destination);
  expect(await db.readRecoveryFile(current, "logs")).toBeNull();
});
