import { mockWebLocks } from "@/test/web-locks";
import { IDBFactory, IDBKeyRange } from "fake-indexeddb";
import { beforeEach, afterEach, expect, it, vi } from "vitest";
import type { CreatedDestination, SubmissionRecoveryMeta } from "@/types/attachment";
import type { IssueRecord } from "@/store/issues-store";

let recovery: typeof import("../submissionRecovery");
let db: typeof import("@/store/blob-db");
let store: typeof import("@/store/issues-store");
const issue = (): IssueRecord => ({ id: "i", title: "Report", platform: "github", status: "draft", createdAt: 1, updatedAt: 1, pageUrl: "", draft: { title: "Report", sections: {} }, snapshot: { before: false, after: false }, captureMode: "freeform" });
const destination: CreatedDestination = { platform: "github", key: "#1", url: "https://github.com/o/r/issues/1", locator: { owner: "o", repo: "r", number: "1" } };
const meta = (): SubmissionRecoveryMeta => ({ attemptId: "a", issueId: "i", title: "Report", platform: "github", createdAt: 1, expiresAt: Date.now() + 2592000000, updatedAt: 1, phase: "prepared", files: [], results: [] });
beforeEach(async () => {
  vi.resetModules();
  mockWebLocks();
  vi.stubGlobal("FileReader", class {
    result = ""; onload = () => {};
    readAsDataURL(blob: Blob) { void blob.arrayBuffer().then((bytes) => { this.result = `data:${blob.type};base64,${Buffer.from(bytes).toString("base64")}`; this.onload(); }); }
  });
  vi.stubGlobal("indexedDB", new IDBFactory());
  vi.stubGlobal("IDBKeyRange", IDBKeyRange);
  const persisted: Record<string, unknown> = {};
  vi.stubGlobal("chrome", { storage: { local: { get: vi.fn(async () => ({ ...persisted })), set: vi.fn(async (values: Record<string, unknown>) => { Object.assign(persisted, values); }) }, session: { get: vi.fn(async () => ({})), set: vi.fn(async () => {}) } }, runtime: { sendMessage: vi.fn() } });
  db = await import("@/store/blob-db");
  store = await import("@/store/issues-store");
  recovery = await import("../submissionRecovery");
  store.useIssuesStore.setState({ issues: [issue()] });
});
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); });

it.each(["inline", "video", "capture", "user"] as const)("missing %s source prevents any external call", async (kind) => {
  const remote = vi.fn();
  const record: IssueRecord = { ...issue(),
    captureMode: kind === "video" ? "video" as const : kind === "capture" ? "screenshot" as const : "freeform" as const,
    draft: { title: "Report", sections: kind === "inline" ? { body: "![image](inline:missing)" } : {} },
    attachments: kind === "user" ? [{ id: "missing", filename: "file.pdf", contentType: "application/pdf", size: 1 }] : [],
  };
  const files = recovery.expectedSubmissionSources(record, { sectionConfig: [{ id: "body", enabled: true, renderAs: "paragraph" }] });
  expect(files).toHaveLength(1);
  await expect(recovery.prepareSubmissionRecovery({ issue: record, platform: "github", files }).then(remote)).rejects.toThrow();
  expect(remote).not.toHaveBeenCalled();
  expect(await db.listSubmissionRecoveries()).toEqual([]);
});
it("freezes generated bytes and stores originals only by their original keys", async () => {
  await db.saveAttachmentBlob("i", "pdf", new Blob(["original"], { type: "application/pdf" }));
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [
    { id: "user:pdf", kind: "user", filename: "logs.html", contentType: "application/pdf", source: { kind: "original", store: "attachments", key: "i:pdf" } },
    { id: "logs", kind: "logs", filename: "logs.html", contentType: "text/html", blob: new Blob(["first"], { type: "text/html" }) },
  ] });
  expect(prepared.meta.files[0].source).toEqual({ kind: "original", store: "attachments", key: "i:pdf" });
  expect(await (await db.readRecoveryFile(prepared.meta, "logs"))!.text()).toBe("first");
  expect(prepared.files.map((f) => f.id)).toEqual(["user:pdf", "logs"]);
});
it("waits for creating and created checkpoints before subsequent adapter work", async () => {
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [] });
  const result = await recovery.runSubmissionRecovery(prepared, async (progress) => {
    await progress.beforeCreate();
    expect((await db.readSubmissionRecovery("i"))?.phase).toBe("creating");
    await progress.created(destination);
    expect((await db.readSubmissionRecovery("i"))?.destination).toEqual(destination);
    return { key: "#1", url: destination.url!, attachments: [] };
  });
  expect(result.key).toBe("#1");
  expect(store.useIssuesStore.getState().issues[0].status).toBe("submitted");
  expect(await db.readSubmissionRecovery("i")).toBeNull();
});
it("preserves created identity when the upload RPC throws", async () => {
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [{ id: "logs", kind: "logs", filename: "logs.html", contentType: "text/html", blob: new Blob(["logs"]) }] });
  const create = vi.fn(async () => destination);
  const result = await recovery.runSubmissionRecovery(prepared, async (progress) => {
    await progress.beforeCreate();
    await progress.created(await create());
    throw new Error("upload disconnected");
  });
  expect(create).toHaveBeenCalledTimes(1);
  expect(result).toMatchObject({ key: "#1", recovery: { state: "partial" } });
  expect((await db.readSubmissionRecovery("i"))?.files).toHaveLength(1);
  expect(store.useIssuesStore.getState().issues[0]).toMatchObject({ status: "submitted", submissionRecoveryId: prepared.meta.attemptId });
});
it("a failed submitted write retains a complete journal and bytes for reconciliation", async () => {
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [] });
  vi.mocked(chrome.storage.local.set).mockRejectedValueOnce(new Error("quota"));
  await expect(recovery.runSubmissionRecovery(prepared, async (p) => { await p.beforeCreate(); await p.created(destination); return { key: "#1", url: destination.url!, attachments: [] }; })).resolves.toMatchObject({ key: "#1", recovery: { state: "partial", storageFailed: true } });
  expect((await db.readSubmissionRecovery("i"))?.phase).toBe("complete");
  await recovery.reconcileSubmissionRecovery();
  expect(store.useIssuesStore.getState().issues[0].status).toBe("submitted");
  expect(await db.readSubmissionRecovery("i")).toBeNull();
});
it("reconciles interrupted creation as unknown and blocks stale drafts", async () => {
  await db.beginSubmissionRecovery(meta(), new Map());
  await db.checkpointSubmission("i", "a", { phase: "creating", results: [] });
  await recovery.reconcileSubmissionRecovery();
  expect((await db.readSubmissionRecovery("i"))?.phase).toBe("unknown");
  expect(store.canSubmitIssue(store.useIssuesStore.getState().issues[0])).toBe(false);
  const remote = vi.fn();
  await expect(store.withIssueSubmitGuard("i", remote)).rejects.toThrow();
  expect(remote).not.toHaveBeenCalled();
});
it("unknown confirmation re-reads and refuses a created destination", async () => {
  await db.beginSubmissionRecovery(meta(), new Map());
  await db.checkpointSubmission("i", "a", { phase: "creating", results: [] });
  await db.checkpointSubmission("i", "a", { phase: "unknown", results: [] });
  await db.checkpointSubmission("i", "a", { phase: "created", results: [], destination });
  await expect(recovery.confirmSubmissionNotRegistered("i", "a")).rejects.toThrow();
  expect((await db.readSubmissionRecovery("i"))?.destination).toEqual(destination);
});
it("expiry drops bytes but retains file names and remote state", async () => {
  const m = meta();
  m.expiresAt = 2;
  m.files = [{ id: "logs", kind: "logs", filename: "logs.html", contentType: "text/html", source: { kind: "generated", key: "file:a:logs" } }];
  await db.beginSubmissionRecovery(m, new Map([["file:a:logs", new Blob(["private"])]]));
  await db.checkpointSubmission("i", "a", { phase: "creating", results: [] });
  await db.checkpointSubmission("i", "a", { phase: "created", destination, results: [] });
  await recovery.reconcileSubmissionRecovery();
  const current = (await db.readSubmissionRecovery("i"))!;
  expect(current.files[0].filename).toBe("logs.html");
  expect(current.destination).toEqual(destination);
  expect(await db.readRecoveryFile(current, "logs")).toBeNull();
});
it("expected sources exclude disabled sections, disabled user files and JSON transmissions", () => {
  const record = { ...issue(), captureMode: "video" as const, draft: { title: "r", sections: { enabled: "![x](inline:one)", disabled: "![x](inline:two)" } }, attachments: [{ id: "pdf", filename: "file.pdf", contentType: "application/pdf", size: 1 }] };
  const options = { sectionConfig: [{ id: "enabled", enabled: true, renderAs: "paragraph" }, { id: "disabled", enabled: false, renderAs: "paragraph" }], attachmentsEnabled: false };
  expect(recovery.expectedSubmissionSources(record, options).map((f) => f.id)).toEqual(["video", "inline:one"]);
  expect(recovery.expectedSubmissionSources(record, { ...options, transmitFiles: false })).toEqual([]);
});
it("download metadata follows the actual original MIME", async () => {
  await db.saveImageBlobRaw("i", "before", new Blob(["jpeg"], { type: "image/jpeg" }));
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [{ id: "capture:screenshot", kind: "capture", filename: "screenshot.webp", contentType: "image/webp", source: { kind: "original", store: "images", key: "i:before" } }] });
  expect(prepared.meta.files[0]).toMatchObject({ filename: "screenshot.jpg", contentType: "image/jpeg" });
});
it("freezes Notion ZIP bytes before any remote work", async () => {
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "notion", files: [{ id: "logs", kind: "logs", filename: "logs.html", contentType: "text/html", blob: new Blob(["<html>frozen</html>"], { type: "text/html" }) }] });
  expect(prepared.meta.files[0]).toMatchObject({ filename: "logs.zip", contentType: "application/zip", source: { kind: "generated" } });
  expect(new Uint8Array(await (await db.readRecoveryFile(prepared.meta, "logs"))!.arrayBuffer()).slice(0, 2)).toEqual(new Uint8Array([80, 75]));
});

it("partial cleanup removes only completed originals after durable list persistence", async () => {
  await db.saveAttachmentBlob("i", "a", new Blob(["done"]));
  await db.saveAttachmentBlob("i", "b", new Blob(["failed"]));
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: ["a", "b"].map((id) => ({ id: `user:${id}`, kind: "user", filename: `${id}.pdf`, contentType: "application/pdf", source: { kind: "original", store: "attachments", key: `i:${id}` } })) });
  await recovery.runSubmissionRecovery(prepared, async (p) => { await p.beforeCreate(); await p.created(destination); return { key: "#1", url: destination.url!, attachments: [
    { fileId: "user:a", delivery: "attached", presentation: "complete" }, { fileId: "user:b", delivery: "failed", presentation: "failed", failure: { stage: "upload", code: "network" } },
  ] }; });
  expect(await db.getAttachmentBlob("i", "a")).toBeNull();
  expect(await (await db.getAttachmentBlob("i", "b"))!.text()).toBe("failed");
  expect(store.useIssuesStore.getState().issues[0].attachments).toBeUndefined();
});
it("reconciliation is idempotent and does not echo-write an unchanged partial record", async () => {
  const m = meta();
  await db.beginSubmissionRecovery(m, new Map());
  await db.checkpointSubmission("i", "a", { phase: "creating", results: [] });
  await db.checkpointSubmission("i", "a", { phase: "created", destination, results: [] });
  await recovery.reconcileSubmissionRecovery();
  const calls = vi.mocked(chrome.storage.local.set).mock.calls.length;
  await recovery.reconcileSubmissionRecovery();
  expect(vi.mocked(chrome.storage.local.set).mock.calls).toHaveLength(calls);
});
it("JSON Webhook acknowledgement retains the draft without recovery files", async () => {
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "webhook", files: [] });
  const result = await recovery.runSubmissionRecovery(prepared, async (p) => { await p.beforeCreate(); return { key: "", url: "", recorded: false, attachments: [] }; });
  expect(result).toMatchObject({ key: "", url: "" });
  expect(await db.readSubmissionRecovery("i")).toBeNull();
  expect(store.useIssuesStore.getState().issues[0].status).toBe("draft");
});
it("a prepared crash is retryable without deleting the original draft bytes", async () => {
  await db.saveVideoBlob("i", new Blob(["video"]));
  await db.beginSubmissionRecovery(meta(), new Map());
  await recovery.reconcileSubmissionRecovery();
  expect(await db.readSubmissionRecovery("i")).toBeNull();
  expect(store.canSubmitIssue(store.useIssuesStore.getState().issues[0])).toBe(true);
  expect(await db.getVideoBlob("i")).not.toBeNull();
});
it("restores a lost list entry from a created journal with provider locator fields", async () => {
  await db.beginSubmissionRecovery(meta(), new Map());
  await db.checkpointSubmission("i", "a", { phase: "creating", results: [] });
  await db.checkpointSubmission("i", "a", { phase: "created", destination, results: [] });
  store.useIssuesStore.setState({ issues: [] });
  await recovery.reconcileSubmissionRecovery();
  expect(store.useIssuesStore.getState().issues[0]).toMatchObject({ id: "i", status: "submitted", key: "#1", githubOwner: "o", githubRepo: "r", submissionRecoveryId: "a" });
});
it("blocks promotion, duplicate submission and deletion during the original submission", async () => {
  let release!: () => void;
  const pending = store.withIssueSubmitGuard("i", () => new Promise<void>((resolve) => { release = resolve; }));
  await vi.waitFor(() => expect(release).toBeDefined());
  expect(store.canSubmitIssue({ ...issue(), status: "submitted", slackPreserved: true })).toBe(false);
  await expect(store.withIssueSubmitGuard("i", async () => {})).rejects.toThrow();
  await expect(store.useIssuesStore.getState().removeIssue("i")).rejects.toThrow();
  await expect(store.useIssuesStore.getState().clearIssues()).rejects.toThrow();
  release();
  await pending;
});
it("successful Slack sharing retains original bytes and permits later promotion", async () => {
  await db.saveAttachmentBlob("i", "pdf", new Blob(["source"]));
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "slack", files: [{ id: "user:pdf", kind: "user", filename: "file.pdf", contentType: "application/pdf", source: { kind: "original", store: "attachments", key: "i:pdf" } }] });
  await recovery.runSubmissionRecovery(prepared, async (p) => { await p.beforeCreate(); await p.created({ platform: "slack", key: "123.4", locator: { channelId: "C1", ts: "123.4" } }); return { key: "123.4", url: "", attachments: [{ fileId: "user:pdf", delivery: "attached", presentation: "complete" }] }; });
  expect(await db.getAttachmentBlob("i", "pdf")).not.toBeNull();
  expect(await db.readSubmissionRecovery("i")).toBeNull();
  expect(store.canSubmitIssue(store.useIssuesStore.getState().issues[0])).toBe(true);
});
it("freezes the Asana JPEG before submission while leaving original webp bytes at their key", async () => {
  await db.saveImageBlobRaw("i", "before", new Blob(["webp"], { type: "image/webp" }));
  const capture = await import("@/sidepanel/capture");
  vi.spyOn(capture, "loadImage").mockResolvedValue({ naturalWidth: 10, naturalHeight: 10 } as HTMLImageElement);
  vi.stubGlobal("document", { createElement: () => ({ width: 0, height: 0, getContext: () => ({ fillRect() {}, drawImage() {}, fillStyle: "" }), toDataURL: () => "data:image/jpeg;base64,anBlZw==" }) });
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "asana", files: [{ id: "capture:screenshot", kind: "capture", filename: "screenshot.webp", contentType: "image/webp", source: { kind: "original", store: "images", key: "i:before" } }] });
  expect(prepared.meta.files[0]).toMatchObject({ filename: "screenshot.jpg", contentType: "image/jpeg", source: { kind: "generated" } });
  expect(await (await db.readRecoveryFile(prepared.meta, "capture:screenshot"))!.text()).toBe("jpeg");
  expect(await (await db.getImageBlob("i", "before"))!.text()).toBe("webp");
});
it("a failed created checkpoint stops follow-up upload and preserves unknown creation", async () => {
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [] });
  const upload = vi.fn();
  const checkpoint = vi.spyOn(db, "checkpointSubmission");
  const result = await recovery.runSubmissionRecovery(prepared, async (p) => {
    await p.beforeCreate();
    checkpoint.mockRejectedValueOnce(new Error("disk failed"));
    await p.created(destination);
    upload();
    return { key: "#1", url: destination.url!, attachments: [] };
  });
  expect(upload).not.toHaveBeenCalled();
  expect(result.recovery?.state).toBe("unknown");
  expect((await db.readSubmissionRecovery("i"))?.phase).toBe("unknown");
});
it("known creation rejection is retryable while ambiguous errors remain unknown", async () => {
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [] });
  await expect(recovery.runSubmissionRecovery(prepared, async (p) => {
    await p.beforeCreate();
    throw new recovery.SubmissionCreationRejectedError();
  })).rejects.toBeInstanceOf(recovery.SubmissionCreationRejectedError);
  expect(await db.readSubmissionRecovery("i")).toBeNull();
  expect(store.canSubmitIssue(store.useIssuesStore.getState().issues[0])).toBe(true);
});

it("does not reconcile or dismiss another live panel's initial submission", async () => {
  let release!: () => void;
  let started!: () => void;
  const ready = new Promise<void>((resolve) => { started = resolve; });
  const create = vi.fn(async () => { started(); await new Promise<void>((resolve) => { release = resolve; }); return destination; });
  const pending = store.withIssueSubmitGuard("i", async () => {
    const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [] });
    return recovery.runSubmissionRecovery(prepared, async (p) => { await p.beforeCreate(); await p.created(await create()); return { key: "#1", url: destination.url!, attachments: [] }; });
  });
  await ready;
  const active = (await db.readSubmissionRecovery("i"))!;
  vi.resetModules();
  const other = await import("../submissionRecovery");
  const otherStore = await import("@/store/issues-store");
  await other.reconcileSubmissionRecovery();
  await expect(other.confirmSubmissionNotRegistered("i", active.attemptId)).rejects.toThrow();
  await expect(otherStore.withIssueSubmitGuard("i", async () => { await create(); })).rejects.toThrow();
  expect((await db.readSubmissionRecovery("i"))?.phase).toBe("creating");
  expect(create).toHaveBeenCalledTimes(1);
  release();
  await pending;
});
it("blocks a stale second panel after completion before storage events arrive", async () => {
  vi.resetModules();
  const otherStore = await import("@/store/issues-store");
  const otherRecovery = await import("../submissionRecovery");
  await otherStore.useIssuesStore.persist.rehydrate();
  expect(otherStore.useIssuesStore.getState().issues[0].status).toBe("draft");
  const create = vi.fn(async () => destination);
  const perform = (s: typeof store, r: typeof recovery) => s.withIssueSubmitGuard("i", async () => {
    const prepared = await r.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [] });
    return r.runSubmissionRecovery(prepared, async (p) => {
      await p.beforeCreate();
      await p.created(await create());
      return { key: destination.key, url: destination.url!, attachments: [] };
    });
  });
  await perform(store, recovery);
  expect(await db.readSubmissionRecovery("i")).toBeNull();
  const completed = await chrome.storage.local.get("bugshot-issues");
  expect(JSON.parse(completed["bugshot-issues"]).state.issues[0]).toMatchObject({ status: "submitted", key: destination.key, url: destination.url });
  expect(otherStore.useIssuesStore.getState().issues[0].status).toBe("draft");
  await expect(perform(otherStore, otherRecovery)).rejects.toBeInstanceOf(otherStore.IssueAlreadySubmittedError);
  expect(create).toHaveBeenCalledTimes(1);
  expect(await chrome.storage.local.get("bugshot-issues")).toEqual(completed);
});
it.each(["read failure", "deleted", "recovery pointer"])("fails closed before preparation on durable %s", async (state) => {
  if (state === "read failure") vi.mocked(chrome.storage.local.get).mockRejectedValueOnce(new Error("read failed"));
  else await chrome.storage.local.set({ "bugshot-issues": JSON.stringify({ state: { issues: state === "deleted" ? [] : [{ ...issue(), submissionRecoveryId: "active" }] }, version: 4 }) });
  const prepare = vi.fn();
  await expect(store.withIssueSubmitGuard("i", prepare)).rejects.toThrow();
  expect(prepare).not.toHaveBeenCalled();
  expect(store.useIssuesStore.getState().issues[0]).toEqual(issue());
});
it("allows durable Slack promotion without replacing newer local fields", async () => {
  store.useIssuesStore.setState({ issues: [{ ...issue(), title: "local edit", updatedAt: 3 }] });
  await chrome.storage.local.set({ "bugshot-issues": JSON.stringify({ state: { issues: [{ ...issue(), status: "submitted", slackPreserved: true, updatedAt: 2 }] }, version: 4 }) });
  await expect(store.withIssueSubmitGuard("i", async () => "promoted")).resolves.toBe("promoted");
  expect(store.useIssuesStore.getState().issues[0].title).toBe("local edit");
});
it("repairs a dangling draft pointer after confirmation deletion and Chrome write failure", async () => {
  await db.beginSubmissionRecovery(meta(), new Map());
  await db.checkpointSubmission("i", "a", { phase: "creating", results: [] });
  await recovery.reconcileSubmissionRecovery();
  const persisted = { ...store.useIssuesStore.getState().issues[0] };
  vi.mocked(chrome.storage.local.set).mockRejectedValueOnce(new Error("quota"));
  await expect(recovery.confirmSubmissionNotRegistered("i", "a")).rejects.toThrow("quota");
  store.useIssuesStore.setState({ issues: [persisted] });
  await recovery.reconcileSubmissionRecovery();
  expect(await db.readSubmissionRecovery("i")).toBeNull();
  expect(store.canSubmitIssue(store.useIssuesStore.getState().issues[0])).toBe(true);
});
it("waits for the exact submitted write before cleanup, then cleans raw logs and residual media", async () => {
  await db.saveVideoBlob("i", new Blob(["unused"]));
  await db.saveImageBlobRaw("i", "before", new Blob(["thumbnail"]));
  await db.saveAttachmentBlob("i", "disabled", new Blob(["disabled file"]));
  await db.saveNetworkLog("i", { id: "n", startedAt: 0, endedAt: 1, totalSeen: 1, captured: 1, requests: [], warnings: [] });
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [] });
  const write = vi.mocked(chrome.storage.local.set).getMockImplementation()! as (values: unknown) => Promise<void>;
  let release!: () => void;
  vi.mocked(chrome.storage.local.set).mockImplementationOnce((values) => new Promise<void>((resolve) => { release = () => { void Promise.resolve(write(values)).then(resolve); }; }));
  const pending = recovery.runSubmissionRecovery(prepared, async (p) => { await p.beforeCreate(); await p.created(destination); return { key: "#1", url: destination.url!, attachments: [] }; });
  await vi.waitFor(() => expect(release).toBeDefined());
  expect((await db.readSubmissionRecovery("i"))?.phase).toBe("complete");
  expect(await db.getNetworkLog("i")).not.toBeNull();
  expect(await db.getVideoBlob("i")).not.toBeNull();
  vi.spyOn(Date, "now").mockReturnValue(store.useIssuesStore.getState().issues[0].updatedAt + 10);
  store.useIssuesStore.getState().patchIssue("i", { title: "unrelated update" });
  await Promise.resolve();
  expect(await db.getNetworkLog("i")).not.toBeNull();
  release();
  await pending;
  expect(await db.getNetworkLog("i")).toBeNull();
  expect(await db.getVideoBlob("i")).toBeNull();
  expect(await db.getImageBlob("i", "before")).toBeNull();
  expect(await db.getAttachmentBlob("i", "disabled")).toBeNull();
  expect(store.useIssuesStore.getState().issues[0].title).toBe("unrelated update");
});
it.each(["networkLogBlobKey", "consoleLogBlobKey", "actionLogBlobKey"] as const)("saved %s missing source blocks the preparation boundary", async (key) => {
  const remote = vi.fn();
  await expect(recovery.loadSubmissionLogs({ ...issue(), [key]: "missing" }).then(remote)).rejects.toBeInstanceOf(recovery.MissingSubmissionFilesError);
  expect(remote).not.toHaveBeenCalled();
  expect(await recovery.loadSubmissionLogs({ ...issue(), [key]: "missing", logsAttached: false })).toEqual({ networkLog: null, consoleLog: null, actionLog: null });
  expect(await recovery.loadSubmissionLogs({ ...issue(), [key]: "missing" }, false)).toEqual({ networkLog: null, consoleLog: null, actionLog: null });
  expect(await recovery.loadSubmissionLogs({ ...issue(), [key]: "missing", captureMode: "element" })).toEqual({ networkLog: null, consoleLog: null, actionLog: null });
});
it("returns the immutable checkpoint destination instead of an inconsistent adapter result", async () => {
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [] });
  const result = await recovery.runSubmissionRecovery(prepared, async (p) => { await p.beforeCreate(); await p.created(destination); return { key: "wrong", url: "https://example.com/wrong", attachments: [] }; });
  expect(result).toMatchObject({ key: destination.key, url: destination.url });
});
it("orphan-pointer reconciliation never downgrades a durably submitted destination", async () => {
  store.useIssuesStore.setState({ issues: [{ ...issue(), submissionRecoveryId: "gone" }] });
  const saved = { ...issue(), status: "submitted" as const, key: "REMOTE-1", url: destination.url, submissionRecoveryId: undefined };
  vi.mocked(chrome.storage.local.get).mockImplementationOnce(async () => ({ "bugshot-issues": JSON.stringify({ state: { issues: [saved] }, version: 5 }) }));
  await recovery.reconcileSubmissionRecovery();
  expect(store.useIssuesStore.getState().issues[0]).toMatchObject({ status: "submitted", key: "REMOTE-1" });
  expect(store.canSubmitIssue(store.useIssuesStore.getState().issues[0])).toBe(false);
});
it.each(["checkpoint", "cleanup", "journal-delete"])("post-create %s failure returns a recovery outcome and can resume cleanup", async (boundary) => {
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [] });
  const result = await recovery.runSubmissionRecovery(prepared, async (p) => {
    await p.beforeCreate(); await p.created(destination);
    if (boundary === "checkpoint") vi.spyOn(db, "checkpointSubmission").mockRejectedValueOnce(new Error("checkpoint unavailable"));
    if (boundary === "cleanup") vi.spyOn(db, "cleanupSubmissionOriginals").mockRejectedValueOnce(new Error("cleanup unavailable"));
    if (boundary === "journal-delete") vi.spyOn(db, "deleteSubmissionRecovery").mockRejectedValueOnce(new Error("delete unavailable"));
    return { key: "#1", url: destination.url!, attachments: [] };
  });
  expect(result).toMatchObject({ key: "#1", url: destination.url, recovery: { state: "partial", storageFailed: true } });
  expect((await db.readSubmissionRecovery("i"))?.destination).toEqual(destination);
  await recovery.reconcileSubmissionRecovery();
  expect(store.useIssuesStore.getState().issues[0].status).toBe("submitted");
  if (boundary !== "checkpoint") expect(await db.readSubmissionRecovery("i")).toBeNull();
});
it("persists canonical permalink enrichment before returning it", async () => {
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [] });
  const { url: _url, ...withoutUrl } = destination;
  const result = await recovery.runSubmissionRecovery(prepared, async (p) => { await p.beforeCreate(); await p.created(withoutUrl); return { key: destination.key, url: destination.url!, attachments: [] }; });
  expect(result.url).toBe(destination.url);
  expect(store.useIssuesStore.getState().issues[0].url).toBe(destination.url);
});
it("post-create journal read failure still returns the known destination", async () => {
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [] });
  const result = await recovery.runSubmissionRecovery(prepared, async (p) => {
    await p.beforeCreate(); await p.created(destination);
    vi.spyOn(db, "readSubmissionRecovery").mockRejectedValueOnce(new Error("read unavailable"));
    return { key: destination.key, url: destination.url!, attachments: [] };
  });
  expect(result).toMatchObject({ key: destination.key, recovery: { state: "partial", storageFailed: true } });
});
it("concurrent initialization and external-sync reconciliation serialize completion cleanup", async () => {
  await db.beginSubmissionRecovery(meta(), new Map());
  await db.checkpointSubmission("i", "a", { phase: "creating", results: [] });
  await db.checkpointSubmission("i", "a", { phase: "created", destination, results: [] });
  await db.checkpointSubmission("i", "a", { phase: "complete", results: [] });
  const cleanup = vi.spyOn(db, "cleanupSubmissionOriginals");
  await Promise.all([recovery.reconcileSubmissionRecovery(), recovery.reconcileSubmissionRecovery()]);
  expect(cleanup).toHaveBeenCalledTimes(1);
  expect(await db.readSubmissionRecovery("i")).toBeNull();
  expect(store.useIssuesStore.getState().issues[0]).toMatchObject({ status: "submitted", key: destination.key, submissionRecoveryId: undefined });
});
it("a newer active attempt prevents stale confirmation and orphan repair from clearing its pointer", async () => {
  await db.beginSubmissionRecovery(meta(), new Map());
  await db.checkpointSubmission("i", "a", { phase: "creating", results: [] });
  await recovery.reconcileSubmissionRecovery();
  await recovery.confirmSubmissionNotRegistered("i", "a");
  let release!: () => void;
  let started!: () => void;
  const ready = new Promise<void>((resolve) => { started = resolve; });
  const pending = store.withIssueSubmitGuard("i", async () => {
    const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [] });
    started();
    await new Promise<void>((resolve) => { release = resolve; });
    return recovery.runSubmissionRecovery(prepared, async (p) => { await p.beforeCreate(); await p.created(destination); return { key: destination.key, url: destination.url!, attachments: [] }; });
  });
  await ready;
  await expect(recovery.confirmSubmissionNotRegistered("i", "a")).rejects.toThrow();
  await recovery.reconcileSubmissionRecovery();
  expect((await db.readSubmissionRecovery("i"))?.attemptId).not.toBe("a");
  release();
  await pending;
});

it.each(["thread", "permalink", "empty", "missing", "success"])("real zero-file Slack %s retains failures independently of file results", async (mode) => {
  const { submitToSlack } = await import("../submitToSlack");
  vi.mocked(chrome.runtime.sendMessage).mockImplementation(((m: { type: string; payload?: { threadTs?: string } }, cb: (r: unknown) => void) => {
    if (m.type === "slack.postMessage") return cb(mode === "thread" && m.payload?.threadTs ? { ok: false, error: "private body", status: 403 } : { ok: true, result: { ts: "1.2" } });
    if (m.type === "slack.getPermalink") return cb(mode === "permalink" ? { ok: false, error: "lost response" } : { ok: true, result: mode === "missing" ? {} : { permalink: mode === "empty" ? "" : "https://slack.com/archives/C/p12" } });
  }) as never);
  const record = { ...issue(), platform: "slack" as const };
  store.useIssuesStore.setState({ issues: [record] });
  const prepared = await recovery.prepareSubmissionRecovery({ issue: record, platform: "slack", files: [] });
  const result = await recovery.runSubmissionRecovery(prepared, (progress) => submitToSlack({ ctx: { bodyLocale: "en", captureMode: "freeform", title: "Title", sections: {}, sectionConfig: [], url: "", selector: "", tagName: "", classListBefore: [], classListAfter: [], specifiedStyles: {}, tokens: [], viewport: { width: 100, height: 100 }, capturedAt: 1, diffs: [], environment: [] }, channelId: "C", submissionFiles: [], progress }));
  if (mode === "success") { expect(result.recovery).toBeUndefined(); expect(await db.readSubmissionRecovery("i")).toBeNull(); return; }
  expect(result).toMatchObject({ key: "1.2", attachments: [], recovery: { state: "partial" } });
  const journal = await db.readSubmissionRecovery("i");
  expect(journal).toMatchObject({ phase: "partial", destination: { locator: { channelId: "C", ts: "1.2" } }, submissionFailure: { stage: "body" } });
  expect(JSON.stringify(journal)).not.toContain("private body");
  await recovery.reconcileSubmissionRecovery();
  expect((await db.readSubmissionRecovery("i"))?.phase).toBe("partial");
});

async function partialSlack() {
  const record = { ...issue(), platform: "slack" as const };
  store.useIssuesStore.setState({ issues: [record] });
  await db.saveAttachmentBlob("i", "pdf", new Blob(["source"]));
  const prepared = await recovery.prepareSubmissionRecovery({ issue: record, platform: "slack", files: [{ id: "user:pdf", kind: "user", filename: "file.pdf", contentType: "application/pdf", source: { kind: "original", store: "attachments", key: "i:pdf" } }] });
  await recovery.runSubmissionRecovery(prepared, async (p) => {
    await p.beforeCreate();
    await p.created({ platform: "slack", key: "1.2", url: "https://slack.com/message", locator: { channelId: "C", ts: "1.2" } });
    throw new Error("upload failed");
  });
  return prepared;
}
it("explicit Slack copy removal releases promotion but preserves submitted source and remote calls stay zero", async () => {
  const prepared = await partialSlack();
  await recovery.deleteSubmissionLocalFiles("i", prepared.meta.attemptId);
  expect(await db.readSubmissionRecovery("i")).toBeNull();
  expect(store.useIssuesStore.getState().issues[0]).toMatchObject({ status: "submitted", slackPreserved: true, key: "1.2", submissionRecoveryId: undefined });
  expect(await (await db.getAttachmentBlob("i", "pdf"))?.text()).toBe("source");
  expect(chrome.runtime.sendMessage).not.toHaveBeenCalled();
  const create = vi.fn();
  await store.withIssueSubmitGuard("i", async () => {
    const next = await recovery.prepareSubmissionRecovery({ issue: store.useIssuesStore.getState().issues[0], platform: "github", files: [] });
    await recovery.runSubmissionRecovery(next, async (p) => { await p.beforeCreate(); create(); await p.created(destination); return { key: "#1", url: destination.url!, attachments: [] }; });
  });
  await expect(store.withIssueSubmitGuard("i", async () => create())).rejects.toThrow();
  expect(create).toHaveBeenCalledOnce();
});
it("expiry alone never releases Slack promotion", async () => {
  const prepared = await partialSlack();
  await db.expireSubmissionRecovery("i", prepared.meta.attemptId, prepared.meta.expiresAt + 1);
  expect((await db.readSubmissionRecovery("i"))?.localFilesRemoved).toBe(true);
  await expect(store.withIssueSubmitGuard("i", async () => {})).rejects.toThrow();
});
it("explicit removal refuses unknown and stale release but still marks unknown files removed", async () => {
  const prepared = await partialSlack();
  await expect(recovery.deleteSubmissionLocalFiles("i", "stale")).rejects.toThrow();
  expect(await db.readSubmissionRecovery("i")).not.toBeNull();
  await recovery.deleteSubmissionLocalFiles("i", prepared.meta.attemptId);
  const next = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "slack", files: [] });
  await recovery.runSubmissionRecovery(next, async (p) => { await p.beforeCreate(); throw new Error("lost"); });
  await recovery.deleteSubmissionLocalFiles("i", next.meta.attemptId);
  expect(await db.readSubmissionRecovery("i")).toMatchObject({ phase: "unknown", localFilesRemoved: true });
  await expect(store.withIssueSubmitGuard("i", async () => {})).rejects.toThrow();
});
it("failed explicit release stays blocked and restart repairs a missing journal", async () => {
  const prepared = await partialSlack();
  vi.mocked(chrome.storage.local.set).mockRejectedValueOnce(new Error("quota"));
  await expect(recovery.deleteSubmissionLocalFiles("i", prepared.meta.attemptId)).rejects.toThrow();
  expect(store.useIssuesStore.getState().issues[0].submissionRecoveryId).toBe(prepared.meta.attemptId);
  await expect(store.withIssueSubmitGuard("i", async () => {})).rejects.toThrow();
  await recovery.reconcileSubmissionRecovery();
  expect(store.useIssuesStore.getState().issues[0]).toMatchObject({ status: "submitted", slackPreserved: true, submissionRecoveryId: undefined });
  expect(await db.getAttachmentBlob("i", "pdf")).not.toBeNull();
});

it("two panels cannot promote twice after explicit Slack recovery removal", async () => {
  const first = await partialSlack();
  await recovery.deleteSubmissionLocalFiles("i", first.meta.attemptId);
  vi.resetModules();
  const otherStore = await import("@/store/issues-store");
  const otherRecovery = await import("../submissionRecovery");
  await otherStore.useIssuesStore.persist.rehydrate();
  const create = vi.fn(async () => destination);
  const perform = (s: typeof store, r: typeof recovery) => s.withIssueSubmitGuard("i", async () => {
    const prepared = await r.prepareSubmissionRecovery({ issue: s.useIssuesStore.getState().issues[0], platform: "github", files: [] });
    return r.runSubmissionRecovery(prepared, async (p) => { await p.beforeCreate(); await p.created(await create()); return { key: destination.key, url: destination.url!, attachments: [] }; });
  });
  await perform(store, recovery);
  expect(otherStore.useIssuesStore.getState().issues[0].platform).toBe("slack");
  await expect(perform(otherStore, otherRecovery)).rejects.toThrow();
  expect(create).toHaveBeenCalledOnce();
});
it("local removal fails closed under the shared active-operation lock", async () => {
  const prepared = await partialSlack();
  await store.withIssueOperationLock("i", async () => {
    await expect(recovery.deleteSubmissionLocalFiles("i", prepared.meta.attemptId)).rejects.toThrow();
    expect((await db.readSubmissionRecovery("i"))?.localFilesRemoved).toBeUndefined();
  });
});

async function partialGithub() {
  await db.saveAttachmentBlob("i", "pdf", new Blob(["source"]));
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [{ id: "user:pdf", kind: "user", filename: "file.pdf", contentType: "application/pdf", source: { kind: "original", store: "attachments", key: "i:pdf" } }] });
  await recovery.runSubmissionRecovery(prepared, async (p) => {
    await p.beforeCreate(); await p.created(destination);
    return { key: destination.key, url: destination.url!, attachments: [{ fileId: "user:pdf", delivery: "failed", presentation: "failed" }] };
  });
  return prepared;
}
it("explicit known non-Slack abandonment clears copies and warning without remote completion claims", async () => {
  const prepared = await partialGithub();
  await recovery.deleteSubmissionLocalFiles("i", prepared.meta.attemptId);
  expect(await db.readSubmissionRecovery("i")).toBeNull();
  expect(store.useIssuesStore.getState().issues[0]).toMatchObject({ status: "submitted", key: "#1", submissionRecoveryId: undefined });
  expect(await db.getAttachmentBlob("i", "pdf")).toBeNull();
  expect(chrome.runtime.sendMessage).not.toHaveBeenCalled();
});
it("non-Slack pointer-clear failure retains a blocked indicator and restart repairs it", async () => {
  const prepared = await partialGithub();
  vi.mocked(chrome.storage.local.set).mockRejectedValueOnce(new Error("quota"));
  await expect(recovery.deleteSubmissionLocalFiles("i", prepared.meta.attemptId)).rejects.toThrow();
  expect(store.useIssuesStore.getState().issues[0].submissionRecoveryId).toBe(prepared.meta.attemptId);
  await recovery.reconcileSubmissionRecovery();
  expect(store.useIssuesStore.getState().issues[0]).toMatchObject({ status: "submitted", key: "#1", submissionRecoveryId: undefined });
});
it("non-Slack TTL retains the warning until explicit abandonment and a stale attempt cannot remove a new journal", async () => {
  const prepared = await partialGithub();
  await db.expireSubmissionRecovery("i", prepared.meta.attemptId, prepared.meta.expiresAt + 1);
  expect(store.useIssuesStore.getState().issues[0].submissionRecoveryId).toBe(prepared.meta.attemptId);
  expect((await db.readSubmissionRecovery("i"))?.phase).toBe("partial");
  await recovery.deleteSubmissionLocalFiles("i", prepared.meta.attemptId);
  const next = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [] });
  await expect(recovery.deleteSubmissionLocalFiles("i", prepared.meta.attemptId)).rejects.toThrow();
  expect((await db.readSubmissionRecovery("i"))?.attemptId).toBe(next.meta.attemptId);
});

it("unknown local removal invalidates mounted consumers through the existing issue store", async () => {
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [] });
  await recovery.runSubmissionRecovery(prepared, async (p) => { await p.beforeCreate(); throw new Error("lost"); });
  const before = store.useIssuesStore.getState().issues[0];
  await recovery.deleteSubmissionLocalFiles("i", prepared.meta.attemptId);
  const after = store.useIssuesStore.getState().issues[0];
  expect(after).not.toBe(before);
  expect(after.updatedAt).toBeGreaterThan(before.updatedAt);
  expect(after.submissionRecoveryId).toBe(prepared.meta.attemptId);
});
it("expiry invalidation preserves newer durable fields and does not echo on repeated reconciliation", async () => {
  const prepared = await partialGithub();
  const local = store.useIssuesStore.getState().issues[0];
  const durable = { ...local, title: "Newer panel title", updatedAt: local.updatedAt + 100 };
  await chrome.storage.local.set({ "bugshot-issues": JSON.stringify({ state: { issues: [durable] }, version: 4 }) });
  await recovery.reconcileSubmissionRecovery(prepared.meta.expiresAt + 1);
  const after = store.useIssuesStore.getState().issues[0];
  expect(after).not.toBe(local);
  expect(after.title).toBe("Newer panel title");
  expect(after.updatedAt).toBeGreaterThan(durable.updatedAt);
  const writes = vi.mocked(chrome.storage.local.set).mock.calls.length;
  await recovery.reconcileSubmissionRecovery(prepared.meta.expiresAt + 1);
  expect(vi.mocked(chrome.storage.local.set).mock.calls).toHaveLength(writes);
});

it("abandonment waits for durable submitted identity before destroying copies", async () => {
  const prepared = await partialGithub();
  await chrome.storage.local.set({ "bugshot-issues": JSON.stringify({ state: { issues: [{ ...issue(), submissionRecoveryId: prepared.meta.attemptId }] }, version: 4 }) });
  vi.mocked(chrome.storage.local.set).mockRejectedValueOnce(new Error("quota"));
  await expect(recovery.deleteSubmissionLocalFiles("i", prepared.meta.attemptId)).rejects.toThrow();
  expect((await db.readSubmissionRecovery("i"))?.phase).toBe("partial");
  expect(await db.getAttachmentBlob("i", "pdf")).not.toBeNull();
  expect(store.useIssuesStore.getState().issues[0].submissionRecoveryId).toBe(prepared.meta.attemptId);
});

it("retains completed generated bytes until a rejected partial submitted write is reconciled", async () => {
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: ["done", "failed"].map((id) => ({ id, kind: "logs", filename: `${id}.html`, contentType: "text/html", blob: new Blob([id]) })) });
  vi.mocked(chrome.storage.local.set).mockRejectedValueOnce(new Error("quota"));
  await recovery.runSubmissionRecovery(prepared, async (p) => {
    await p.beforeCreate(); await p.created(destination);
    return { key: "#1", url: destination.url!, attachments: [
      { fileId: "done", delivery: "attached", presentation: "complete" },
      { fileId: "failed", delivery: "failed", presentation: "failed", failure: { stage: "upload", code: "network" } },
    ] };
  });
  expect(await (await db.readRecoveryFile(prepared.meta, "done"))?.text()).toBe("done");
  expect(await (await db.readRecoveryFile(prepared.meta, "failed"))?.text()).toBe("failed");
  await recovery.reconcileSubmissionRecovery();
  expect(await db.readRecoveryFile(prepared.meta, "done")).toBeNull();
  expect(await (await db.readRecoveryFile(prepared.meta, "failed"))?.text()).toBe("failed");
  expect(store.useIssuesStore.getState().issues[0].status).toBe("submitted");
});

it("Slack partial runner releases completed generated logs but preserves original attachments", async () => {
  await db.saveAttachmentBlob("i", "pdf", new Blob(["original"]));
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "slack", files: [
    { id: "user:pdf", kind: "user", filename: "file.pdf", contentType: "application/pdf", source: { kind: "original", store: "attachments", key: "i:pdf" } },
    { id: "logs", kind: "logs", filename: "logs.html", contentType: "text/html", blob: new Blob(["generated"]) },
  ] });
  const result = await recovery.runSubmissionRecovery(prepared, async (p) => {
    await p.beforeCreate();
    await p.created({ platform: "slack", key: "1", url: "https://slack.com/archives/C1/p1", locator: { channelId: "C1", ts: "1" } });
    return { key: "1", url: "https://slack.com/archives/C1/p1", attachments: [
      { fileId: "logs", delivery: "attached", presentation: "complete" },
      { fileId: "user:pdf", delivery: "failed", presentation: "failed", failure: { stage: "upload", code: "network" } },
    ] };
  });
  expect(result.recovery?.state).toBe("partial");
  expect(await db.readRecoveryFile(prepared.meta, "logs")).toBeNull();
  expect(await (await db.getAttachmentBlob("i", "pdf"))?.text()).toBe("original");
  expect(store.useIssuesStore.getState().issues[0]).toMatchObject({ status: "submitted", slackPreserved: true });
});

const logsIntent = () => ({ id: "logs", kind: "logs" as const, filename: "logs.html", contentType: "text/html", blob: new Blob(["l"], { type: "text/html" }) });
const answerIdentity = (reply: (msg: { type: string }) => unknown) => vi.mocked(chrome.runtime.sendMessage).mockImplementation(((msg: { type: string }, cb: (r: unknown) => void) => { cb(reply(msg)); }) as never);
const partialResult = { key: "#1", url: destination.url!, attachments: [{ fileId: "logs", delivery: "failed" as const, presentation: "failed" as const, failure: { stage: "upload" as const, code: "permission" as const, httpStatus: 403 } }] };

it("snapshots the submitted bodyLocale and persists file checkpoints before the next adapter step", async () => {
  answerIdentity(() => ({ ok: false, error: "offline" }));
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [logsIntent()] });
  // Captured inside, asserted outside: the run converts adapter exceptions into results.
  let afterUpload: SubmissionRecoveryMeta["retry"];
  let afterBody: SubmissionRecoveryMeta["retry"];
  await recovery.runSubmissionRecovery(prepared, async (progress) => {
    const input = recovery.withSubmissionProgress({ ctx: { bodyLocale: "ko" as const } }, progress, prepared.files);
    await input.progress.fileCheckpoint({ fileId: "logs", upload: "done", uploaded: { platform: "github", href: "https://github.com/user-attachments/files/1/logs.html" } });
    afterUpload = (await db.readSubmissionRecovery("i"))!.retry;
    await input.progress.beforeCreate();
    await input.progress.created(destination);
    await input.progress.bodyWritten("created body");
    afterBody = (await db.readSubmissionRecovery("i"))!.retry;
    return partialResult;
  });
  expect(afterUpload).toMatchObject({ bodyLocale: "ko", accountIdentity: null, revision: 1, bodyPlan: { format: "markdown", lastWritten: "" } });
  expect(afterUpload!.checkpoints).toEqual([{ fileId: "logs", upload: "done", link: "not-applicable", body: "pending", uploaded: { platform: "github", href: "https://github.com/user-attachments/files/1/logs.html" } }]);
  expect(afterBody!.bodyPlan.lastWritten).toBe("created body");
});

it("resolves the account identity only for a partial result and stores it in the snapshot", async () => {
  answerIdentity(() => ({ ok: true, result: { identity: '["github","42"]' } }));
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [logsIntent()] });
  const result = await recovery.runSubmissionRecovery(prepared, async (progress) => {
    const input = recovery.withSubmissionProgress({ ctx: { bodyLocale: "en" as const } }, progress, prepared.files);
    await input.progress.beforeCreate();
    await input.progress.created(destination);
    return partialResult;
  });
  expect(result.recovery).toMatchObject({ state: "partial" });
  expect(vi.mocked(chrome.runtime.sendMessage).mock.calls.map(([m]) => m)).toEqual([{ type: "github.getAccountIdentity", destination }]);
  expect((await db.readSubmissionRecovery("i"))!.retry!.accountIdentity).toBe('["github","42"]');
});

it("keeps a partial submission intact when the identity lookup fails", async () => {
  answerIdentity(() => ({ ok: false, error: "401", status: 401 }));
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [logsIntent()] });
  const result = await recovery.runSubmissionRecovery(prepared, async (progress) => {
    const input = recovery.withSubmissionProgress({ ctx: { bodyLocale: "en" as const } }, progress, prepared.files);
    await input.progress.beforeCreate();
    await input.progress.created(destination);
    return partialResult;
  });
  expect(result).toMatchObject({ key: "#1", recovery: { state: "partial" } });
  expect(result.recovery?.storageFailed).toBeUndefined();
  const meta = (await db.readSubmissionRecovery("i"))!;
  expect(meta.phase).toBe("partial");
  expect(meta.retry!.accountIdentity).toBeNull();
});

it("makes no identity request for a complete submission", async () => {
  answerIdentity(() => ({ ok: true, result: { identity: '["github","42"]' } }));
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [logsIntent()] });
  await recovery.runSubmissionRecovery(prepared, async (progress) => {
    const input = recovery.withSubmissionProgress({ ctx: { bodyLocale: "en" as const } }, progress, prepared.files);
    await input.progress.beforeCreate();
    await input.progress.created(destination);
    return { key: "#1", url: destination.url!, attachments: [{ fileId: "logs", delivery: "attached", presentation: "complete" }] };
  });
  expect(chrome.runtime.sendMessage).not.toHaveBeenCalled();
  expect(await db.readSubmissionRecovery("i")).toBeNull();
});

it("records no snapshot without a bound bodyLocale or for webhook", async () => {
  for (const platform of ["github", "webhook"] as const) {
    const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform, files: [logsIntent()] });
    let stored: SubmissionRecoveryMeta | null = null;
    await recovery.runSubmissionRecovery(prepared, async (progress) => {
      const bound = platform === "webhook" ? recovery.withSubmissionProgress({ ctx: { bodyLocale: "en" as const } }, progress, prepared.files).progress : progress;
      await bound.fileCheckpoint({ fileId: "logs", upload: "failed" });
      stored = await db.readSubmissionRecovery("i");
      throw new Error("stop before creation");
    }).catch(() => {});
    expect(stored).not.toBeNull();
    expect(stored!.retry).toBeUndefined();
  }
});

it("disables auto-retry instead of failing the submission when a retry checkpoint cannot be stored", async () => {
  answerIdentity(() => ({ ok: true, result: { identity: '["github","42"]' } }));
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [logsIntent()] });
  const result = await recovery.runSubmissionRecovery(prepared, async (progress) => {
    const input = recovery.withSubmissionProgress({ ctx: { bodyLocale: "en" as const } }, progress, prepared.files);
    await input.progress.beforeCreate();
    await input.progress.created(destination);
    await input.progress.fileCheckpoint({ fileId: "not-in-journal", upload: "failed" });
    await input.progress.bodyWritten("later body");
    return partialResult;
  });
  expect(result).toMatchObject({ key: "#1", recovery: { state: "partial" } });
  expect(result.recovery?.storageFailed).toBeUndefined();
  expect(chrome.runtime.sendMessage).not.toHaveBeenCalled();
  const retry = (await db.readSubmissionRecovery("i"))!.retry!;
  expect(retry.accountIdentity).toBeNull();
  expect(retry.bodyPlan.lastWritten).toBe("");
});

it("resolves a hanging identity lookup to null after 10 seconds and still completes the partial result", async () => {
  vi.useFakeTimers({ toFake: ["setTimeout", "clearTimeout"] });
  try {
    const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "github", files: [logsIntent()] });
    let settled = false;
    const run = recovery.runSubmissionRecovery(prepared, async (progress) => {
      const input = recovery.withSubmissionProgress({ ctx: { bodyLocale: "en" as const } }, progress, prepared.files);
      await input.progress.beforeCreate();
      await input.progress.created(destination);
      return partialResult;
    }).finally(() => { settled = true; });
    await vi.waitFor(() => expect(chrome.runtime.sendMessage).toHaveBeenCalledTimes(1));
    await vi.advanceTimersByTimeAsync(9_999);
    expect(settled).toBe(false);
    await vi.advanceTimersByTimeAsync(1);
    const result = await run;
    expect(result.recovery).toMatchObject({ state: "partial" });
    const meta = (await db.readSubmissionRecovery("i"))!;
    expect(meta.phase).toBe("partial");
    expect(meta.retry!.accountIdentity).toBeNull();
  } finally {
    vi.useRealTimers();
  }
});

it("removes a stale uploaded locator when a patch clears it", async () => {
  answerIdentity(() => ({ ok: false, error: "offline" }));
  const prepared = await recovery.prepareSubmissionRecovery({ issue: issue(), platform: "slack", files: [logsIntent()] });
  let checkpoint: unknown;
  await recovery.runSubmissionRecovery(prepared, async (progress) => {
    const input = recovery.withSubmissionProgress({ ctx: { bodyLocale: "en" as const } }, progress, prepared.files);
    await input.progress.beforeCreate();
    await input.progress.created({ platform: "slack", key: "1.2", locator: { channelId: "C", ts: "1.2" } });
    await input.progress.fileCheckpoint({ fileId: "logs", upload: "pending", uploaded: { platform: "slack", id: "F1" } });
    await input.progress.fileCheckpoint({ fileId: "logs", upload: "failed", uploaded: undefined });
    checkpoint = (await db.readSubmissionRecovery("i"))!.retry!.checkpoints[0];
    return { key: "1.2", url: "", attachments: [{ fileId: "logs", delivery: "failed", presentation: "failed", failure: { stage: "upload", code: "unknown" } }] };
  });
  expect(checkpoint).toStrictEqual({ fileId: "logs", upload: "failed", link: "pending", body: "not-applicable" });
});
