import { afterEach, expect, it, vi } from "vitest";
import { render, screen, waitFor, within, cleanup } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { IDBFactory, IDBKeyRange } from "fake-indexeddb";
import { mockWebLocks } from "@/test/web-locks";
import type { IssueRecord } from "@/store/issues-store";
vi.mock("@/i18n", async (original) => ({ ...await original<typeof import("@/i18n")>(), useT: () => (key: string) => key }));
vi.mock("../statusBadges/SubmittedBadge", () => ({ SubmittedBadge: () => <span>Submitted</span> }));
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
it("confirmed non-Slack abandonment removes the actual persistent pointer, row warning and count", async () => {
  vi.resetModules();
  mockWebLocks();
  vi.stubGlobal("indexedDB", new IDBFactory());
  vi.stubGlobal("IDBKeyRange", IDBKeyRange);
  const saved: Record<string, unknown> = {};
  const remote = vi.fn();
  vi.stubGlobal("chrome", { storage: { local: { get: async () => ({ ...saved }), set: async (values: Record<string, unknown>) => { Object.assign(saved, values); } }, session: { get: async () => ({}) } }, runtime: { sendMessage: remote } });
  const db = await import("@/store/blob-db");
  const { useIssuesStore } = await import("@/store/issues-store");
  const { useSettingsStore } = await import("@/store/settings-store");
  const { IssueListTab } = await import("../IssueListTab");
  await useIssuesStore.persist.rehydrate();
  await useSettingsStore.persist.rehydrate();
  useSettingsStore.setState({ accounts: {} });
  const record: IssueRecord = { id: "i", title: "Report", platform: "github", key: "#1", url: "https://github.com/o/r/issues/1", status: "submitted", submissionRecoveryId: "a", createdAt: 1, updatedAt: 1, pageUrl: "", draft: { title: "Report", sections: {} }, snapshot: { before: false, after: false } };
  useIssuesStore.setState({ issues: [record] });
  await db.beginSubmissionRecovery({ issueId: "i", attemptId: "a", title: "Report", platform: "github", phase: "prepared", createdAt: 1, updatedAt: 1, expiresAt: Date.now() + 10000, files: [], results: [] }, new Map());
  await db.checkpointSubmission("i", "a", { phase: "creating", results: [] });
  await db.checkpointSubmission("i", "a", { phase: "created", destination: { platform: "github", key: "#1", url: record.url, locator: { owner: "o", repo: "r", number: "1" } }, results: [] });
  await db.checkpointSubmission("i", "a", { phase: "partial", results: [], submissionFailure: { stage: "body", code: "network" } });
  render(<IssueListTab />);
  expect(screen.getByTestId("filter-submitted").textContent).toContain("(1)");
  await userEvent.click(screen.getByTestId("recovery-detail-open"));
  await userEvent.click(await screen.findByTestId("recovery-delete-local"));
  await userEvent.click(within(screen.getByRole("alertdialog")).getByRole("button", { name: "recovery.deleteLocal" }));
  await waitFor(() => expect(screen.queryByTestId("recovery-row-warning")).toBeNull());
  expect(screen.getByTestId("filter-submitted").textContent).not.toContain("(1)");
  await waitFor(() => expect(screen.queryByTestId("draft-detail-dialog")).toBeNull());
  expect(screen.queryByTestId("detail-submit-open")).toBeNull();
  expect(useIssuesStore.getState().issues[0].submissionRecoveryId).toBeUndefined();
  expect(await db.readSubmissionRecovery("i")).toBeNull();
  expect(JSON.parse(saved["bugshot-issues"] as string).state.issues[0].status).toBe("submitted");
  expect(remote).not.toHaveBeenCalled();
});

it("unknown removal updates both mounted row and detail while keeping creation blocked", async () => {
  vi.resetModules();
  mockWebLocks();
  vi.stubGlobal("indexedDB", new IDBFactory());
  vi.stubGlobal("IDBKeyRange", IDBKeyRange);
  const saved: Record<string, unknown> = {};
  vi.stubGlobal("chrome", { storage: { local: { get: async () => ({ ...saved }), set: async (values: Record<string, unknown>) => { Object.assign(saved, values); } }, session: { get: async () => ({}) } }, runtime: { sendMessage: vi.fn() } });
  const db = await import("@/store/blob-db");
  const { useIssuesStore, withIssueSubmitGuard } = await import("@/store/issues-store");
  const { useSettingsStore } = await import("@/store/settings-store");
  const { IssueListTab } = await import("../IssueListTab");
  const { AttachmentRecoveryPanel } = await import("@/sidepanel/components/AttachmentRecoveryPanel");
  await useIssuesStore.persist.rehydrate();
  await useSettingsStore.persist.rehydrate();
  useSettingsStore.setState({ accounts: {} });
  const record: IssueRecord = { id: "i", title: "Report", platform: "github", status: "draft", submissionRecoveryId: "a", createdAt: 1, updatedAt: 1, pageUrl: "", draft: { title: "Report", sections: {} }, snapshot: { before: false, after: false } };
  useIssuesStore.setState({ issues: [record] });
  await db.beginSubmissionRecovery({ issueId: "i", attemptId: "a", title: "Report", platform: "github", phase: "prepared", createdAt: 1, updatedAt: 1, expiresAt: Date.now() + 10000, files: [], results: [] }, new Map());
  await db.checkpointSubmission("i", "a", { phase: "creating", results: [] });
  await db.checkpointSubmission("i", "a", { phase: "unknown", results: [] });
  render(<><IssueListTab /><AttachmentRecoveryPanel issueId="i" attemptId="a" allowManage /></>);
  await userEvent.click(await screen.findByTestId("recovery-delete-local"));
  await userEvent.click(within(screen.getByRole("alertdialog")).getByRole("button", { name: "recovery.deleteLocal" }));
  await waitFor(() => expect(screen.getByTestId("recovery-row-warning").textContent).toContain("recovery.localMissing"));
  expect(screen.getAllByText("recovery.localMissing")).toHaveLength(2);
  expect(screen.getByTestId("filter-submitted").textContent).toContain("(1)");
  await expect(withIssueSubmitGuard("i", async () => {})).rejects.toThrow();
});
