import { IDBFactory, IDBObjectStore } from "fake-indexeddb";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { SubmissionRecoveryMeta } from "@/types/attachment";

let db: typeof import("../blob-db");
const meta = (issueId = "issue", attemptId = "attempt"): SubmissionRecoveryMeta => ({
  issueId, attemptId, title: "Report", platform: "github", createdAt: 1, expiresAt: 2592000001,
  phase: "prepared", updatedAt: 1, files: [], results: [],
});
const open = (version = 9) => new Promise<IDBDatabase>((resolve, reject) => {
  const req = indexedDB.open("bugshot-video", version);
  req.onsuccess = () => resolve(req.result);
  req.onerror = () => reject(req.error);
});
const keys = async () => {
  const conn = await open();
  return new Promise<IDBValidKey[]>((resolve, reject) => {
    const tx = conn.transaction("submissionRecovery");
    const req = tx.objectStore("submissionRecovery").getAllKeys();
    tx.oncomplete = () => { conn.close(); resolve(req.result); };
    tx.onerror = () => { conn.close(); reject(tx.error); };
  });
};
beforeEach(async () => {
  vi.resetModules();
  vi.stubGlobal("indexedDB", new IDBFactory());
  vi.stubGlobal("chrome", { storage: { session: { get: async () => ({}) }, local: { get: async () => ({}) } } });
  db = await import("../blob-db");
});
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); });

describe("submission recovery storage", () => {
  it("creates and cleans even an empty-file journal", async () => {
    await db.beginSubmissionRecovery(meta(), new Map());
    expect(await db.listSubmissionRecoveries()).toEqual([meta()]);
    await db.deleteSubmissionRecovery("issue", "attempt");
    expect(await db.readSubmissionRecovery("issue")).toBeNull();
    expect(await keys()).toEqual([]);
  });
  it("serializes concurrent begin and rejects stale checkpoint and delete", async () => {
    const outcomes = await Promise.allSettled([
      db.beginSubmissionRecovery(meta(), new Map()), db.beginSubmissionRecovery(meta("issue", "second"), new Map()),
    ]);
    expect(outcomes.map((v) => v.status).sort()).toEqual(["fulfilled", "rejected"]);
    const current = (await db.readSubmissionRecovery("issue"))!;
    await expect(db.checkpointSubmission("issue", "stale", { phase: "creating", results: [] })).rejects.toThrow();
    await expect(db.deleteSubmissionRecovery("issue", "stale")).rejects.toThrow();
    expect(await db.readSubmissionRecovery("issue")).toEqual(current);
    await db.deleteSubmissionRecovery("issue", current.attemptId);
    await expect(db.checkpointSubmission("issue", current.attemptId, { phase: "creating", results: [] })).rejects.toThrow();
  });
  it("checks transitions and preserves a created destination", async () => {
    await db.beginSubmissionRecovery(meta(), new Map());
    await expect(db.checkpointSubmission("issue", "attempt", { phase: "complete", results: [] })).rejects.toThrow();
    await db.checkpointSubmission("issue", "attempt", { phase: "creating", results: [] });
    const destination = { platform: "github" as const, key: "repo#1", locator: { owner: "o", repo: "r", number: "1" } };
    await db.checkpointSubmission("issue", "attempt", { phase: "created", destination, results: [] });
    await db.checkpointSubmission("issue", "attempt", { phase: "partial", results: [] });
    expect((await db.readSubmissionRecovery("issue"))?.destination).toEqual(destination);
    await expect(db.checkpointSubmission("issue", "attempt", { phase: "creating", results: [] })).rejects.toThrow();
  });
  it("stores generated bytes once without copying original bytes", async () => {
    await db.saveVideoBlob("issue", new Blob(["original"]));
    const value = meta();
    value.files = [
      { id: "video", kind: "video", filename: "video.mp4", contentType: "video/mp4", source: { kind: "original", store: "blobs", key: "issue" } },
      { id: "logs", kind: "logs", filename: "logs.html", contentType: "text/html", source: { kind: "generated", key: "file:attempt:logs" } },
    ];
    await db.beginSubmissionRecovery(value, new Map([["file:attempt:logs", new Blob(["first logs"])]]));
    expect(await keys()).toEqual(["attempt:issue", "file:attempt:logs"]);
    expect(await (await db.readRecoveryFile(value, "video"))?.text()).toBe("original");
    expect(await (await db.readRecoveryFile(value, "logs"))?.text()).toBe("first logs");
    await db.deleteSubmissionRecovery("issue", "attempt");
    expect(await (await db.getVideoBlob("issue"))?.text()).toBe("original");
    expect(await db.readRecoveryFile(value, "video")).toBeNull();
  });
  it("rolls back metadata and preceding generated files when a put fails", async () => {
    const value = meta();
    value.files = ["a", "b"].map((id) => ({ id, kind: "logs", filename: id, contentType: "text/html", source: { kind: "generated", key: `file:attempt:${id}` } }));
    const originalPut = IDBObjectStore.prototype.put;
    vi.spyOn(IDBObjectStore.prototype, "put").mockImplementation(function (this: IDBObjectStore, value, key) {
      if (key === "file:attempt:b") throw new DOMException("Full", "QuotaExceededError");
      return originalPut.call(this, value, key);
    });
    await expect(db.beginSubmissionRecovery(value, new Map([["file:attempt:a", new Blob(["a"])], ["file:attempt:b", new Blob(["b"])]]))).rejects.toThrow("Full");
    expect(await keys()).toEqual([]);
  });
  it("protects original keys against legacy deletion and inline GC until explicitly released", async () => {
    await db.saveVideoBlob("orphan", new Blob(["video"]));
    await db.saveImageBlob("orphan", "before", new Blob(["image"]));
    await db.saveInlineImage("ref", new Blob(["inline"]));
    await db.saveAttachmentBlob("orphan", "a", new Blob(["user"]));
    const value = meta();
    value.files = [
      ["video", "blobs", "orphan"], ["capture", "images", "orphan:before"],
      ["inline", "inlineImages", "ref"], ["user", "attachments", "orphan:a"],
    ].map(([kind, store, key]) => ({ id: kind, kind, filename: kind, contentType: "application/octet-stream", source: { kind: "original", store, key } })) as SubmissionRecoveryMeta["files"];
    await db.beginSubmissionRecovery(value, new Map());
    await Promise.all([db.deleteVideoBlob("orphan"), db.deleteImageBlobs("orphan"), db.deleteAttachmentBlobs("orphan"), db.deleteAttachmentBlob("orphan", "a"), db.pruneOrphanInlineImages([])]);
    await Promise.all([db.clearVideoBlobs(), db.clearImageBlobs(), db.clearAttachmentBlobs(), db.clearInlineImages()]);
    for (const file of value.files) expect(await db.readRecoveryFile(value, file.id)).not.toBeNull();
    await db.deleteOriginalKeys([value.files[0].source]);
    expect(await db.getVideoBlob("orphan")).toBeNull();
    expect(await db.getImageBlob("orphan", "before")).not.toBeNull();
    await db.purgeRecoveryForIssues(["issue"]);
    expect(await db.getImageBlob("orphan", "before")).toBeNull();
    expect(await db.getInlineImage("ref")).toBeNull();
    expect(await db.getAttachmentBlob("orphan", "a")).toBeNull();
    expect(await keys()).toEqual([]);
  });
  it("upgrades v8 without losing existing stores and closes on versionchange", async () => {
    const req = indexedDB.open("bugshot-video", 8);
    req.onupgradeneeded = () => {
      for (const name of ["blobs", "images", "networkLogs", "consoleLogs", "actionLogs", "inlineImages", "inlineImageOrigins", "attachments"]) req.result.createObjectStore(name);
      req.transaction!.objectStore("blobs").put(new Blob(["v8"]), "old");
    };
    await new Promise<void>((resolve) => { req.onsuccess = () => { req.result.close(); resolve(); }; });
    await db.beginSubmissionRecovery(meta(), new Map());
    expect(await (await db.getVideoBlob("old"))?.text()).toBe("v8");
    const upgraded = await open(10);
    upgraded.close();
  });
  it("rejects a blocked upgrade with panel-close guidance and recovers after it closes", async () => {
    const old = await open(8);
    await expect(db.beginSubmissionRecovery(meta(), new Map())).rejects.toThrow(/close.*BugShot panels/i);
    old.close();
    await db.beginSubmissionRecovery(meta(), new Map());
    expect(await db.readSubmissionRecovery("issue")).not.toBeNull();
  });
});
